<!-- add by web_lover -->

<p class="form-row form-row-wide">
 <div>
    <label for="kbis">KBis</label>
    <input type="file" name="kbis" id="kbis" accept = "application/pdf, image/*">
 </div>

 <div>
    <label for="identity_doc">Document d'identité</label>
    <input type="file" name="identity_doc" id="identity_doc" accept = "application/pdf, image/*">
 </div>

</p>

<!-- end add by web_lover -->

<?php

# web_lover file upload part
# For example we are processing form action here
# Include the follwing and then do this

require_once(ABSPATH . 'wp-admin/includes/image.php');
require_once(ABSPATH . 'wp-admin/includes/file.php');
require_once(ABSPATH . 'wp-admin/includes/media.php');
		
# web_lover for kbis file 

if ( ! empty( $_FILES['kbis'] ) ) {
    $uploaded_file = $_FILES['kbis'];
    $allowed_types = array( 'image/jpeg', 'image/png', 'application/pdf' );
    $upload_overrides = array( 'test_form' => false );

    $filetype = wp_check_filetype( $uploaded_file['name'], null );
    if ( in_array( $filetype['type'], $allowed_types ) ) {
        $movefile = wp_handle_upload( $uploaded_file, $upload_overrides );

        if ( $movefile && ! isset( $movefile['error'] ) ) {
            echo 'File kbis is valid, and was successfully uploaded.';

			echo "<pre>";
			print_r($movefile);
			echo "</pre>";
        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            echo $movefile['error'];
        }
    } else {
        echo 'Invalid kbis file type.';
    }
}
# end web_lover for kbis file

# web_lover for identity_doc file 

if ( ! empty( $_FILES['identity_doc'] ) ) {
    $uploaded_file = $_FILES['identity_doc'];
    $allowed_types = array( 'image/jpeg', 'image/png', 'application/pdf' );
    $upload_overrides = array( 'test_form' => false );

    $filetype = wp_check_filetype( $uploaded_file['name'], null );
    if ( in_array( $filetype['type'], $allowed_types ) ) {
        $movefile = wp_handle_upload( $uploaded_file, $upload_overrides );

        if ( $movefile && ! isset( $movefile['error'] ) ) {
            echo 'File identity document is valid, and was successfully uploaded.';
            
			echo "<pre>";
			print_r($movefile);
			echo "</pre>";

        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            echo $movefile['error'];
        }
    } else {
        echo 'Invalid identity_doc file type.';
    }
}
# end web_lover for identity_doc file